version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  test:
    docker:
      - image: cimg/node:12.22.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

workflows:
  sample:
    jobs:
      - test